### ISSUE TITLE
[Watchmarket] Add logic to fallback to other price providers

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/watchmarket#100]
watchmarket needs to be able to fallback to available price, if not available on CMC => check CG, if not available on CG => check Binance Chain for price. This would be the most logical path to get correct price from our providers.

If not available on one provider - it does not mean the rest should fail too. This should be adjustable for any coin or provider

**Comment by EnoRage** [comment]
Good point, was mentioned here as well
https://github.com/trustwallet/watchmarket/issues/83

**Comment by EnoRage** [comment]
Solved at #101
