### ISSUE TITLE
[API] Add support to specify multiple assets in GET request

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/watchmarket#143]
Extend `https://market.trustwallet.com/v2/market/ticker/c60,c0,c714?currency=USD` API to support passing multiple assets

**Comment by vikmeup** [comment]
It's probably worth using this scheme: `v2/market/tickers` to support both GET and POST

**Comment by EnoRage** [comment]
Done

**Comment by EnoRage** [comment]
We use query instead of /token
