### ISSUE TITLE
Improve deployment

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/watchmarket#185]
- [ ] Consolidate all apis (api-charts, api-rates, api-tickers, api-swagger) into `api`, on all levels, development and deployment. Rule of thumb: 1 binary = 1 micro service / pod
- [ ] Remove nginx
- [ ] Fix docker compose and remove seed from docker compose (https://github.com/trustwallet/watchmarket/blob/master/docker-compose.yml#L111), add separate command to run seed
- [ ] Improve config naming, change `my_db` to `watchmarket` (https://github.com/trustwallet/watchmarket/blob/master/docker-compose.yml#L11)

`$api/swagger` will need to contain public documentation endpoint

**Comment by EnoRage** [comment]
https://github.com/trustwallet/watchmarket/pull/190
