### ISSUE TITLE
createCgCoinsMap function code bug

### ISSUE THREAD

**Issue by zyjblockchain** [trustwallet/watchmarket#404]
![image](https://user-images.githubusercontent.com/40423181/110090524-5c4bae80-7dd2-11eb-92b6-14f24b51c656.png)
There is append slice but not recover. because one token could have multiple platform and need to be record

**Comment by vikmeup** [comment]
Would you be able to create PR for this issue?

**Comment by zyjblockchain** [comment]
> Would you be able to create PR for this issue?
