### ISSUE TITLE
[API Extensions] Slush bucket to collect API changes

### ISSUE THREAD

**Issue by arein** [trustwallet/watchmarket#46]
There are a few ideas on how to improve the API. Collecting them here:
1. Allow to query by symbol: right now you need to provide coin IDs e.g. `coin=60` (ETH) in your request payload. It would be nice to allow the option to query by symbol e.g. `symbol=eth`
2. Allow to request data from a specific provider: e.g. provider=cmc to retrieve coinmarketcap data only
3. Provide a "max_age" parameter: only return data more recent than the max age

**Comment by arein** [comment]
@EnoRage @vikmeup please collect further API improvement ideas here

**Comment by EnoRage** [comment]
1. According to @vikmeup there is no need in it => we do not need endpoints that nobody wants
2. Same as @vikmeup said
3. Good idea, but we will implement them using Cache control policy for headers
