### ISSUE TITLE
[Market-atlas] Price of Taps not showing 

### ISSUE THREAD

**Issue by POSHCOIN** [trustwallet/watchmarket#5]
![Screenshot_20200206-050520](https://user-images.githubusercontent.com/58894055/73905036-49e50580-489e-11ea-8636-b82934afe3dc.png)

https://www.coingecko.com/en/coins/tapspay (price is available) but not showing on trustwallet wallet
0x56bB6f961F2CB9947FEa063Df1A42c2233487903

**Comment by EnoRage** [comment]
Works fine RN
