### ISSUE TITLE
[Store] Make universal format for storing values

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/watchmarket#96]
Current PR's https://github.com/trustwallet/watchmarket/pull/95, https://github.com/trustwallet/watchmarket/pull/94 show as unreliable current structure is, small changes could easily break parsing of storing data.

Solution to use
- lowercase format for all stored keys
- remove any logic that is related to checksum and etc
- return data in the format user requested.

Example:
```
Example 1: 
request: 60:0x1A3 
response: 60:0x1A3 price is 0.1

Example 2: 
request: 60:0x1a3 
response: 60:0x1a3 price is 0.1
```

@EnoRage can share more context and ideal on this issue.

**Comment by EnoRage** [comment]
Solved at #101
